[package]
name = "shared-interfaces"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
soroban-sdk = { version = "21.0.0" }

[dev-dependencies]
soroban-sdk = { version = "21.0.0", features = ["testutils"] }
